# Generated by Django 2.0 on 2021-03-24 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='products/')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('salary', models.FloatField()),
                ('depid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='shoppingsite.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='products/')),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('pic1', models.ImageField(upload_to='products/')),
                ('pic2', models.ImageField(upload_to='products/')),
                ('pic3', models.ImageField(upload_to='products/')),
                ('pic4', models.ImageField(upload_to='products/')),
                ('mrp', models.IntegerField()),
                ('sellingprice', models.IntegerField()),
                ('description', models.CharField(max_length=800)),
                ('specification', models.CharField(default='', max_length=600)),
                ('tag', models.CharField(choices=[('new', 'new'), ('best', 'best'), ('featured', 'featured'), ('top', 'top'), ('popular', 'popular'), ('stylish', 'stylish'), ('trending', 'trending'), ('awesome', 'awesome'), ('beautiful', 'beautiful')], max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('available', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Preorder', 'Preorder')], max_length=200)),
                ('genreid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingsite.genre')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('pid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingsite.products')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='products/')),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingsite.category')),
            ],
            options={
                'db_table': 'subcategory',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='subcatid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingsite.subcategory'),
        ),
        migrations.AddField(
            model_name='comment',
            name='productid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shoppingsite.products'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
