# Generated by Django 2.0 on 2021-04-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingsite', '0003_auto_20210409_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcatid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategoryname', to='shoppingsite.subcategory'),
        ),
    ]
