# Generated by Django 2.0 on 2021-05-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingsite', '0004_auto_20210415_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('pic', models.ImageField(upload_to='blog/')),
                ('cdate', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
